### ISSUE TITLE
@fairstep decorator should act as a strict validator of a python function

### ISSUE THREAD

**Issue by raar1** [fair-workflows/fairworkflows#121]
* It should enforce that type hinting is used, as well as any other issues that would stop it being converted to a FairStep.
* This should be a requirement for anything that gets converted with ```FairStep.from_function()```
* The Extension would not publish a cell if it did not contain a method with a ```@fairstep```

**Comment by svenvanderburg** [comment]
Use `FairStep` decorator to mark a function as a fairstep. This will also validate the function (for example for having type hints).
```python
@FairStep(label='Summing')
def sum(a: int, b: int) -> int:
    """Sum inputs"""
    return a + b
```

Create a fair step object and access its properties:
```python
step = FairStep.from_function(sum)
print('label: ' + step.label)
print('description: ' + step.description)
```
> label: Summing
> description: Sum inputs

Publishing the step:
```python
step.publish_as_nanopub()
```

Adding it to a workflow:
```python
workflow.add(step)
```

**Comment by svenvanderburg** [comment]
When injecting python code corresponding to a fair step into the notebook using the notebook extension we want it to inject code similar to how we declared it, so including the decorator. Maybe we could inject a derived_from attribute so it is explicit that it is derived from another nanopub.
```python
@FairStep(label='Summing', derived_from='www.example.nl/original-nanopub')
def sum(a: int, b: int) -> int:
    """Sum inputs"""
    return a + b
```

**Comment by tkuhn** [comment]
Option 1 looks perfect to me! Validation upon setting the decorator would be really nice (but is probably not the most urgent feature).

Option 2 is indeed very confusing and Python programmers would rightly hate us for it.

Option 3 is less explicit and will give the impression that any function can be turned be turned into a workflow step without changes, which is not what we want.

**Comment by tkuhn** [comment]
Summary: +1 for Option 1.

**Comment by svenvanderburg** [comment]
My point was that Option 1 is not feasible, and Option 2 fixes that. (and both option 1 and 2 are gonna be hated by python programmers) 😄

**Comment by tkuhn** [comment]
Sorry, I overlooked that. But why is "define properties of the fairstep (i.e. label='Summing') in the decorator" not feasible?

**Comment by rcelebi** [comment]
If I try to summarize what I understand from the discussions:

What makes a function FAIR is that the metadata of the function is sufficiently defined. That's why we don't want to publish a function without its FAIR metadata. So there are possibly two ways that users can define FAIR step: 
1 ) Some users can add the metadata as a part of decorator, and then publish it with UI using the Jupyter extension. They would also expect to retrieve/see a FAIR step with its metadata from  Jupyter extension.
2) More technical users can generate a FAIR step from a function ( from_function() ) and publish it by using the programmatic API ( publish_as_nanopub() ) by adding more metadata. Also, they can create/compose a workflow and publish that workflow.

You can mix these two approaches, that requires taking option 1 or 2.

**Comment by tkuhn** [comment]
I imagine something like this, illustrated with Python code snippets (this is my first time using decorators, so I might do stupid and embarrassing stuff here):

```python
def fairstep(label=""):
    def fairstep_x(func):
        print("Validating step: " + label)
        def wrapper(*args, **kwargs):
            print("Running step: " + label)
            result = func(*args, **kwargs)
            return result
        return wrapper
    return fairstep_x
```

```python
@fairstep(label="foobar")
def sum(a: int, b: int) -> int:
    """Sum inputs"""
    return a + b
```

Validating step: foobar

```python
sum(1,2)
```

Running step: foobar

3

And then for the `FairStep.from_function(sum)` part I imagine we can use Python's inspection features to get the info we need. I suppose that we can also get the decorator arguments from that. But I might be misunderstanding some things here, as I have never used these inspections in Python either.

**Comment by svenvanderburg** [comment]
OK, I realised I phrased things a bit awkward by using the word 'feasible'. I think implementing option 1 is possible, i.e. one could implement it, I think @tkuhn's decorator is a good start (props for your python skills). A decorator like this is not the problem though. The problem is the inspection part. That is indeed probably possible, but it opens a can of worms:
* There is an implicit/hidden state (namely the arguments for the decorator) that will be vital for the functionality that is stored in the guts of python. This can lead to all kinds of unexpected behaviour.
* The code to implement this will become complex (mostly because of the implicit coupling of `from_function` to the arguments of the function and the arguments of the decorator), and thus hard to maintain.

Some advantages:
* That being said there are python libraries that implement this kind of 'magic' (like for example `pytest`) because the idea behind it are clear.
*The advantage of option 1 is that you can still call the function (like @tkuhn  also points out in the code snippet). For option 2 we would have to have a method `call()` for calling the function itself. Or `execute()` to also track provenance.

Regarding @rcelebi's point that a fair function should come with sufficient metdata: we already validate a fair step before publishing. But I like the idea of already doing validation when declaring a fair function using the decorator.

I suggest to implement both option 1 and 2 and then compare.

**Comment by tkuhn** [comment]
OK, I see. Yes, it felt like the guts of Python when I was (insuccessfully) trying to figure out how reflection worked...

I have to admit that I was very confused about the decorators, because they look like Java annotations and seem to behave in the same way. But then I realized they are really different (even though they can sometimes be used for the same purpose).

I learned a lot about Python since yesterday! :) (but still lots more to learn...)

And I stumbled about this possibility to solve our problem (maybe, if I got this right):

```python
def fairstep(label=""):
    def fairstep_x(func):
        print("Validating step: " + label)
        def wrapper(*args, **kwargs):
            print("Running step: " + label)
            result = func(*args, **kwargs)
            return result
        wrapper.label = label
        return wrapper
    return fairstep_x
```

The only difference is the line `wrapper.label = label`.

Then, with the same step definition above, we can now additionally do this:

```python
sum.label
```

And it returns our metadata value `foobar`. And we can do this of course similarly for all the arguments we want to support (or just have one single big dictionary). No more Python guts.

That would be a clean version of Option 1, or am I missing something?

**Comment by tkuhn** [comment]
We could even do `sum.stepobject` to return the step object as in Option 2, but now `sum` would still be normally executable as a function.

**Comment by svenvanderburg** [comment]
Nice @tkuhn! Very creative use of what is possible with python. 😄 This feels completely wrong to me, but I agree that this is explicit, and it is debatable how bad this actually is, see [this stackoverflow answer and discussion](https://stackoverflow.com/a/338145/4711118). We will implement something like this and compare it with option 2.
