### ISSUE TITLE
Support loading multiple steps described in the same nanopublication

### ISSUE THREAD

**Issue by raar1** [fair-workflows/fairworkflows#88]
It appears that some nanopublications may contain rdf describing 2 or more steps. We would like to find a way to support loading these as separate FairSteps.

**Comment by svenvanderburg** [comment]
@raar1 do you have an example of this? That would make it much easier to reproduce this. I think this should already work actually if you pass the url#frag?

**Comment by raar1** [comment]
Hmm actually I think I was imagining giving a nanopublication that introduced several steps, and producing several FairStep objects from it, but as we at present only support one concept being introduced that would need to wait. Also, maybe it's not necessary? I suppose in principle the from_rdf class method could return a list? Or is that an abuse of the pattern?

**Comment by svenvanderburg** [comment]
Yeah assuming one concept being introduced at a time would make this obsolete.
Otherwise you could do this:
```python
step1 = FairStep.from_nanopub(http://purl.org/np/id#step1)
step2 = FairStep.from_nanopub(http://purl.org/np/id#step2)
```
I think that is the cleanest way to do this. I've created https://github.com/fair-workflows/fairworkflows/issues/96 because this will always copy all RDF statements even though they might not be relevant.

**Comment by raar1** [comment]
I agree. #96 is a good issue, as that does need sorted out. I'll close this issue now.
